# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5oNvgnYRNS8uWx_KbdN0d3cJQ3aPAm6
"""

from collections import Counter

def calculate_word_frequency(text):
    # Convert the text to lowercase and split it into words
    words = text.lower().split()

    # Remove pu
    words = [word.strip('.,!?;:"()[]{}') for word in words]
    word_counts = Counter(words)
    for word, count in word_counts.items():
        print(f"{word}: {count}")
text = input("Enter a block of text: ")
calculate_word_frequency(text)