# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VipMa40yk2kaY8_Jzlr-1PR4f8vQmd6L
"""

import re

def clean_text(text):
    cleaned_text = re.sub(r'[,!.@]', '', text)

    cleaned_text = cleaned_text.lower()

    return cleaned_text

input_text = 'Hello, World! Welcome to NLP 101.'
cleaned_text = clean_text(input_text)

print("Original Text:", input_text)
print("Cleaned Text:", cleaned_text)

