# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DD_hI2eow4HdEVLLC4BETF49Me9yKXfC
"""

import nltk

nltk.download('punkt')

paragraph = """Natural Language Processing (NLP) is a fascinating field of study.
It involves the interaction between computers and humans using natural language.
There are many applications of NLP, such as sentiment analysis, language translation, and chatbots."""

sentences = nltk.sent_tokenize(paragraph)

words = nltk.word_tokenize(paragraph)

print("Original Paragraph:", paragraph)
print("\nTokenized Sentences:", sentences)
print("\nTokenized Words:", words)

nltk.download('punkt_tab')

