# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKq7n_RoBrirWxSZExhYbNvSIDXpr29_
"""

import numpy as np
import pandas  as pd

df = pd.read_csv('/content/sentiment_analysis.csv')

df

df['sentiment'].unique()

df['sentiment'].value_counts()

from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

# Download required resources for nltk
nltk.download('vader_lexicon')

# Initialize SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

# Download required resources for nltk
nltk.download('vader_lexicon')

# Initialize SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer

from nltk.sentiment import SentimentIntensityAnalyzer

# Initialize the SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

sentence = "This is by far the worst movie that I saw."
sentiment_scores = sia.polarity_scores(sentence)
print(sentiment_scores)

df['prediction_score'] = df['review'].apply(lambda x: sia.polarity_scores(x)['compound

pip install textblob

from textblob import TextBlob

